/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.friscic.zavrsnirad.view;

/**
 *
 * @author K1R4
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
        jmNaslovGrana.setText((Aplikacija.NASLOV_APP));
        setTitle("SMV APP");

        jmiOperateri.setVisible(Aplikacija.isAdmin());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmNaslovGrana = new javax.swing.JMenu();
        jmiKlijenti = new javax.swing.JMenuItem();
        jmiVozila = new javax.swing.JMenuItem();
        jmiServisi = new javax.swing.JMenuItem();
        jmiRadnici = new javax.swing.JMenuItem();
        jmiMarke = new javax.swing.JMenuItem();
        jmiOperateri = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmiIzlaz = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 426));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\K1R4\\Downloads\\peter-broomfield-m3m-lnR90uM-unsplash.jpg")); // NOI18N

        jmNaslovGrana.setText("GLAVNI IZBORNIK");

        jmiKlijenti.setText("Klijenti");
        jmiKlijenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKlijentiActionPerformed(evt);
            }
        });
        jmNaslovGrana.add(jmiKlijenti);

        jmiVozila.setText("Vozila");
        jmiVozila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVozilaActionPerformed(evt);
            }
        });
        jmNaslovGrana.add(jmiVozila);

        jmiServisi.setText("Servisi");
        jmNaslovGrana.add(jmiServisi);

        jmiRadnici.setText("Radnici");
        jmiRadnici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRadniciActionPerformed(evt);
            }
        });
        jmNaslovGrana.add(jmiRadnici);

        jmiMarke.setText("Marke");
        jmiMarke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMarkeActionPerformed(evt);
            }
        });
        jmNaslovGrana.add(jmiMarke);

        jmiOperateri.setText("Operateri");
        jmiOperateri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOperateriActionPerformed(evt);
            }
        });
        jmNaslovGrana.add(jmiOperateri);
        jmNaslovGrana.add(jSeparator4);

        jmiIzlaz.setText("Izlaz");
        jmiIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzlazActionPerformed(evt);
            }
        });
        jmNaslovGrana.add(jmiIzlaz);

        jMenuBar1.add(jmNaslovGrana);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzlazActionPerformed
        dispose();
    }//GEN-LAST:event_jmiIzlazActionPerformed

    private void jmiOperateriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOperateriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiOperateriActionPerformed

    private void jmiKlijentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKlijentiActionPerformed
        new Klijenti().setVisible(true);
    }//GEN-LAST:event_jmiKlijentiActionPerformed

    private void jmiRadniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRadniciActionPerformed
        new Radnici().setVisible(true);
    }//GEN-LAST:event_jmiRadniciActionPerformed

    private void jmiMarkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMarkeActionPerformed
        new Marke().setVisible(true);
    }//GEN-LAST:event_jmiMarkeActionPerformed

    private void jmiVozilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVozilaActionPerformed
        new Vozila().setVisible(true);
    }//GEN-LAST:event_jmiVozilaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu jmNaslovGrana;
    private javax.swing.JMenuItem jmiIzlaz;
    private javax.swing.JMenuItem jmiKlijenti;
    private javax.swing.JMenuItem jmiMarke;
    private javax.swing.JMenuItem jmiOperateri;
    private javax.swing.JMenuItem jmiRadnici;
    private javax.swing.JMenuItem jmiServisi;
    private javax.swing.JMenuItem jmiVozila;
    // End of variables declaration//GEN-END:variables
}
